### ISSUE TITLE
Lag with magnet

### ISSUE THREAD

**Issue by LemADEC** [UniversalLP/JustEnoughButtons#23]
On a good dedicated server with a single player online and having magnet on, using justenoughbuttons-1.10.2-1.7.1, we can observe 3% CPU load just due to magnet handling:
![image](https://cloud.githubusercontent.com/assets/4776032/23651223/21dbbafa-0325-11e7-9dd1-902872f74e02.png)

**Comment by univrsal** [comment]
I ran a profiler on a local server and I couldn't even find the event calls but there's no doubt that my code is inefficient.
But I can't think of any other approach for the magnet mode, the only thing that I could think of that would help with performance is a delay between the magnet mode calls.

**Comment by LemADEC** [comment]
I was checking an area after removing tree logs, so there was a lot of saplings and sticks on the floor.
getEntitiesWithinAABB() is known to be badly implemented.
Since there's generally way more entities than players, it's probably more efficient to inverse the scan into something like:
```
for all worlds
   if no listed players, then skip
   for all entities
      if not entityItem, then skip
      for all players
         xxxx
```

**Comment by univrsal** [comment]
Are you sure that iterating over all entities in a world would be faster than only getting the ones in a predefined area? [Botania](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMagnetRing.java#L84) for example is doing it the same way only with a delay. So I'd guess that I should just check for items like every 10th event call

**Comment by LemADEC** [comment]
We need to reduce the calls to getEntitiesWithinAABB(), either do it less frequently like Botania, or re-implement the latest. If you choose to do the former, remember you need to also give a motion to the item instead of just setting it's position since entities will fall during 2 updates.

**Comment by univrsal** [comment]
Alrighty I'll see if I can figure out the profiler to test out both ways

**Comment by univrsal** [comment]
So I added a line to reduce the calls of getEntitiesWithinAABB and reduced the priority of the Subscribe event. The magnet mode still works fine for me so I don't see a need to add velocity, since it's still picking up items pretty consistently.

After some fiddling to figure out the profiler it seems to me that the cpu usage is now pretty insignificant:

![unbenannt](https://cloud.githubusercontent.com/assets/8353672/23800457/c50a0824-05ac-11e7-8712-bcced5785da8.PNG)

But since I'm not very familiar with profiling, you might wanna give the new build another try.

**Comment by LemADEC** [comment]
will do

**Comment by univrsal** [comment]
Since I didn't get any response I'll just close this for now
